### ISSUE TITLE
liquid-fire compatibility for {{remember-document-scroll}}

### ISSUE THREAD

**Issue by billdami** [ef4/memory-scroll#12]
It seems that the `{{remember-document-scroll}}` component is not compatible with liquid-fire when used together with `{{liquid-outlet}}` and route transition animations. My guess is that the write to `document.scrollTop` is happening too early, since its invoked immediately upon the component render, and not waiting until after the liquid-fire transition is complete?

I did verify that removing the liquid-outlets did result in the remember-document-scroll working correctly. So if the above suspicion is correct, is this something that could be easily solved by overriding the remember-document-scroll component? Perhaps if liquid-fire provides any sort of hook/event that gets fired once the route transition is fully complete?

**Comment by nickschot** [comment]
Also seeing this in my testing. Have you by any chance implemented some kind of workaround? I might fiddle with it myself too.

**Edit:** I'm seeing that the position is actually remembered too late (combined with a scroll-to 0 in the target route) causing 0 to be saved instead of the actual scroll position.

Call order I'm seeing:
1. new page {{scroll-to}}
2. old page {{remember-document-scroll}}

This likely has to do with liquid-fire delaying the destruction of the old component (?) as the position is saved in the willDestroyElement hook.

**Comment by villander** [comment]
Can you put an example on ember-twiddle for me to check?

**Comment by nickschot** [comment]
I'll create one later this week!
