### ISSUE TITLE
Update ember-cli to last version

### ISSUE THREAD

**Issue by villander** [ef4/memory-scroll#6]
@ef4 what you think about updated ember-cli version(for example 2.6.2)? I can do this :D 

I think that this addon can be more util to community and evolved over time. 
How  we can support the version 1.x forward? I think that we can to offer support just 2.x forward

**Comment by ef4** [comment]
That sounds great, go for it.

That said, the version of ember-cli used within the addon doesn't matter very much to users of the addon. It only matters for the dummy app and for people developing the addon.

As far as I know, this addon is compatible with all version of ember-cli, because it doesn't do anything interesting on the node side of things.

**Comment by villander** [comment]
Ok @ef4, make sense for me.
I will do update to last version of ember-cli, to hereafter we publish our dummy app as [ember-cp-validations](http://offirgolan.github.io/ember-cp-validations/)

**Comment by villander** [comment]
Done @ef4  #7
